### ISSUE TITLE
Remove `unsafe_disable_continuation_linearity_check` feature

### ISSUE THREAD

**Issue by dhil** [wasmfx/wasmfxtime#230]
This feature is really a hack for benchmarking that was useful before we had stack-allocated continuation objects.

**Comment by frank-emrich** [comment]
Yes, let's get rid of it.

As far as I remember the performance gain of disabling the linearity check is only ~6% ever since we moved to the fat pointer implementation. We should re-measure this when we remove the feature, just for future reference.
